title: Jade's Home 
subtitle: Be quick,don't be hurry! 
link: 博客URL
meta:
  description: 页面meta中的description
  keywords: !!seq
    - 关键词1
    - 关键词2
    - 关键词3
  author: 页面meta中的author
master:
  name: jade
  about: 又一个程序猿 
  email: 邮箱
tags:
  - node.js  
rss:
  title: RSS源标题
  desc: RSS源描述
  lang: zh-cn
  max: 10
copyright:
  owner: 版权所有方
  beginYear: 2013
  endYear: 2013
  ICP: 沪ICP备08321413号 
theme: default
codetheme: night
